version: "2"
services:
    hugo_server:
        extends:
            file: hugo.yml
            service: hugo
        ports:
            - 1313:1313
        network_mode: "host"
        command: ["hugo", "server", "-wDs", "./"]
    hugo_deploy:
        extends:
            file: hugo.yml
            service: hugo
        command: ["hugo", "-wD", "-d", "../public_html"]

